// WeatherIconMappings.js

export const weatherIconMappings = {
    conditionIcons: {
        null: 'n/a',
        DZ: 'drizzle',
        RA: 'rain',
        SN: 'snow',
        SG: 'snow grains',
        IC: 'ice crystals',
        PL: 'ice pellets',
        GR: 'hail',
        GS: 'small hail/snow pellets',
        UP: 'unknown precipitation',
        BR: 'mist',
        FG: 'fog',
        FU: 'smoke',
        VA: 'volcanic ash',
        SA: 'sand',
        HZ: 'haze',
        PY: 'spray',
        DU: 'widespread dust',
        SQ: 'squall',
        SS: 'sandstorm',
        DS: 'duststorm',
        PO: 'well-developed dust/sand whirls',
        FC: 'funnel cloud',
        '+FC': 'tornado/waterspout',
        '-': 'light',
        '+': 'heavy',
        VC: 'in vicinity:',
        MI: 'shallow',
        BC: 'patches',
        SH: 'showers',
        PR: 'partial',
        TS: 'thunderstorm',
        BL: 'blowing',
        DR: 'drifting',
        FZ: 'freezing',
    },
    cloudIcons: {
        null: 'n/a',
        SKC: 'clear sky',
        CLR: 'clear sky',
        FEW: 'few clouds',
        SCT: 'scattered clouds',
        BKN: 'broken clouds',
        OVC: 'overcast',
        CAVOK: 'clouds and visibility OK',
        NCD: 'no clouds detected',
        NSC: 'nil significant cloud',
        VV: 'vertical visibility',
    },
};